---
name: publish
on:
  push:
    branches-ignore:
      - '*'
    tags:
      - 'v[0-9]*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Get image tags
        id: image_tags
        run: |
          # Version is a semantic version tag or semantic version with release number
          # GITHUB_REF will be of the form "refs/tags/v0.1.2" or "refs/tags/v0.1.2-1"
          # To determine VERSION, strip off the leading "refs/tags/"
          VERSION=${GITHUB_REF#refs/tags/}

          echo "IMAGE_TAGS=latest ${VERSION%.*} ${VERSION}" >> $GITHUB_OUTPUT

      - name: Buildah Action
        id: buildah-build
        if: steps.image_tags.outputs.IMAGE_TAGS
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ vars.IMAGE_NAME }}
          tags: ${{ steps.image_tags.outputs.IMAGE_TAGS }}
          dockerfiles: Dockerfile
      

      - name: Push image to registry
        id: push-to-registry
        if: steps.image_tags.outputs.IMAGE_TAGS
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.buildah-build.outputs.image }}
          tags: ${{ steps.buildah-build.outputs.tags }}
          registry: ${{ vars.IMAGE_REGISTRY }}/${{ vars.IMAGE_REPOSITORY }}
          username: ${{ secrets.IMAGE_REGISTRY_USERNAME }}
          password: ${{ secrets.IMAGE_REGISTRY_PASSWORD }}
